apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netcortex.fullname" . }}-data
  labels:
    {{- include "netcortex.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistence.data.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
