apiVersion: v1
kind: Service
metadata:
  name: {{ include "netcortex.fullname" . }}-web
  labels:
    {{- include "netcortex.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "netcortex.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
